version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.16.0
    - 7.19.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.2
    - 11.2.3
  - dependency-name: next-pwa
    versions:
    - 5.0.2
    - 5.0.4
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
